// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDYjagye2J2xVTwMIt_sAPh5g6qrmAyVyk',
//     appId: '1:608055589041:web:45c63de0dcf86ac34a0a90',
//     messagingSenderId: '608055589041',
//     projectId: 'vexa-eleicoes',
//     authDomain: 'vexa-eleicoes.firebaseapp.com',
//     databaseURL: 'https://vexa-eleicoes-default-rtdb.firebaseio.com',
//     storageBucket: 'vexa-eleicoes.appspot.com',
//     measurementId: 'G-WRBGFXFT3M',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAK1Ubrt_3T4KhA5bybCikdc8gfcsDfdZw',
//     appId: '1:608055589041:android:ff360644486dff094a0a90',
//     messagingSenderId: '608055589041',
//     projectId: 'vexa-eleicoes',
//     databaseURL: 'https://vexa-eleicoes-default-rtdb.firebaseio.com',
//     storageBucket: 'vexa-eleicoes.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBYfwDKqT5aJrkiUd7EAprVgeKHO56jz7k',
//     appId: '1:608055589041:ios:e165734a37344cab4a0a90',
//     messagingSenderId: '608055589041',
//     projectId: 'vexa-eleicoes',
//     databaseURL: 'https://vexa-eleicoes-default-rtdb.firebaseio.com',
//     storageBucket: 'vexa-eleicoes.appspot.com',
//     iosClientId: '608055589041-7s2bmierf9i6geqpq3b0a0ql9uelug65.apps.googleusercontent.com',
//     iosBundleId: 'com.example.vexaEleicoes',
//   );
// }
